### ISSUE TITLE
fastify.Plugin Namespace has no exported member 'Plugin'.

### ISSUE THREAD

**Issue by harveyconnor** [fastify/fastify-cors#83] opened 2020-08-20 07:10 UTC
## 🐛 Bug Report

Trying to compile my code with Typescript however I keep receiving the following issue:
```
node_modules/fastify-cors/index.d.ts:18:36 - error TS2694: Namespace '"/Users/harvey/devproject/node_modules/fastify/fastify"' has no exported member 'Plugin'.
```
The error is on line 18 
```
18 declare const fastifyCors: fastify.Plugin<
```

## To Reproduce

```js
tsc
```

## Expected behavior

I expect it to not throw the error and grab the Plugin type correctly.

## Your Environment

- *node version*: 12
- *fastify version*: >=3.0.0
- *os*: Mac
- *any other relevant information*

**Comment by harveyconnor** [comment] 2020-08-20 07:11
I have tried installing `fastify-plugin` as well however that does not resolve the issue.

**Comment by fox1t** [comment] 2020-08-20 07:12
Thanks for sharing this bug. Can you provide a repro repository so I can start to look into this?

**Comment by fox1t** [comment] 2020-08-20 09:00
I can't reproduce this. Which version of `fastify-cors` are you using? I suspect that it is not compatible with fastify > v3

**Comment by fox1t** [comment] 2020-08-20 09:07
OK confirmed, you are using version 3.x.x of `fastify-cors` on fastify v3. 

Upgrade `fastify-cors` to v4 and you will be fine.
Closing this.

**Closed by fox1t** 2020-08-20 09:07 UTC

**Comment by harveyconnor** [comment] 2020-08-20 10:08
Yep v4 did the trick!
Could you please document this somewhere as when I ran `npm install fastify-cors` it chose v3 by default.

**Comment by fox1t** [comment] 2020-08-20 10:10
Strange that it installed v3 by default. How long ago did you `npm I fastify-cors`?

**Comment by harveyconnor** [comment] 2020-08-20 23:54
Only recently, it may have found a rogue cached version on my system that I previously installed a while ago. Not sure.
Would be good to have a compatibility table on the readme just so people don't download the wrong version and waste time trying to discover a solution.

**Comment by splacentino** [comment] 2020-11-04 07:11
I still have the issue at Typescript build time

```
$ tsc --build
../node_modules/fastify-cors/index.d.ts:3:10 - error TS2305: Module '"../fastify/fastify"' has no exported member 'FastifyPlugin'.

3 import { FastifyPlugin } from 'fastify'
           ~~~~~~~~~~~~~
```

Versions are:
```
    "fastify": "^3.7.0",
    "fastify-cors": "^4.1.0",
```
